"""Initial migration

Revision ID: 91430c8f04b4
Revises: 
Create Date: 2025-10-06 01:23:20.837774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91430c8f04b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создание таблицы users
    op.create_table('users',
        sa.Column('userid', sa.BigInteger(), nullable=False),
        sa.Column('group', sa.String(length=50), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('daily_notify_enabled', sa.Boolean(), nullable=True),
        sa.Column('notification_time', sa.String(length=50), nullable=True),
        sa.Column('notify_online', sa.Boolean(), nullable=True),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('tutorial_completed', sa.Boolean(), nullable=True),
        sa.Column('subgroup', sa.Integer(), nullable=True, comment='1 или 2 — выбранная подгруппа'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('userid')
    )
    
    # Создание таблицы chats
    op.create_table('chats',
        sa.Column('chatid', sa.BigInteger(), nullable=False),
        sa.Column('thread_id', sa.BigInteger(), nullable=True),
        sa.Column('group', sa.String(length=50), nullable=False),
        sa.Column('daily_notify_enabled', sa.Boolean(), nullable=True),
        sa.Column('notification_time', sa.String(length=50), nullable=True),
        sa.Column('notify_online', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('chatid')
    )
    
    # Создание таблицы blocked_users
    op.create_table('blocked_users',
        sa.Column('userid', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('userid')
    )
    op.create_index('idx_blocked_at', 'blocked_users', ['blocked_at'], unique=False)
    
    # Создание таблицы holidays
    op.create_table('holidays',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('group', sa.String(length=50), nullable=False),
        sa.Column('start_date', sa.String(length=20), nullable=False),
        sa.Column('end_date', sa.String(length=20), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создание таблицы semester_boundaries
    op.create_table('semester_boundaries',
        sa.Column('group', sa.String(length=50), nullable=False),
        sa.Column('first_date', sa.String(length=20), nullable=False),
        sa.Column('last_date', sa.String(length=20), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('group')
    )
    
    # Создание таблицы personalized_names
    op.create_table('personalized_names',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # Создание таблицы global_groups
    op.create_table('global_groups',
        sa.Column('group_name', sa.String(length=50), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('group_name')
    )
    
    # Создание таблицы bans
    op.create_table('bans',
        sa.Column('userid', sa.BigInteger(), nullable=False),
        sa.Column('ban_until', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('userid')
    )
    
    # Создание таблицы patterns
    op.create_table('patterns',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('pattern', sa.Text(), nullable=False),
        sa.Column('response', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создание таблицы alerted_lessons
    op.create_table('alerted_lessons',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('chatid', sa.BigInteger(), nullable=False),
        sa.Column('date', sa.String(length=20), nullable=False),
        sa.Column('start_time', sa.String(length=20), nullable=False),
        sa.Column('sbj', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Создание таблицы admin_users
    op.create_table('admin_users',
        sa.Column('userid', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('userid')
    )
    
    # Создание таблицы admin_permissions
    op.create_table('admin_permissions',
        sa.Column('userid', sa.BigInteger(), nullable=False),
        sa.Column('command', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['userid'], ['admin_users.userid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('userid', 'command'),
        sa.UniqueConstraint('userid', 'command', name='uq_userid_command')
    )
    
    # Создание таблицы feedback_messages
    op.create_table('feedback_messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('user_message_id', sa.Integer(), nullable=True),
        sa.Column('media_ids', sa.Text(), nullable=True),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаление таблиц в обратном порядке
    op.drop_table('feedback_messages')
    op.drop_table('admin_permissions')
    op.drop_table('admin_users')
    op.drop_table('alerted_lessons')
    op.drop_table('patterns')
    op.drop_table('bans')
    op.drop_table('global_groups')
    op.drop_table('personalized_names')
    op.drop_table('semester_boundaries')
    op.drop_table('holidays')
    op.drop_index('idx_blocked_at', table_name='blocked_users')
    op.drop_table('blocked_users')
    op.drop_table('chats')
    op.drop_table('users')
    
    # ### end Alembic commands ###
